from . import mixin_stock_model
from . import product_template
from . import stock_location
from . import product_product
from . import procurement
from . import stock_quant
from . import stock_warehouse
from . import stock_move_line
from . import stock_quant_package
from . import stock_picking
from . import stock_move
from . import res_users
from . import stock_picking_type
from . import stock_location_category
from . import stock_warehouse_orderpoint
from . import stock_production_lot
