from . import allowed_file_type
from . import ir_actions
from . import ir_attachment
from . import models
from . import readonly_desktop_user_exception
from . import res_authentication_attempt
from . import res_groups
from . import res_partner
from . import res_users
