# -*- coding: utf-8 -*-
{
    "name": "UDES Stock",
    "summary": "udes stock",
    "description": "Core models and configuration for UDES Stock - Odoo 14",
    "author": "Unipart digital",
    "website": "http://github/unipartdigital/udes-open",
    "category": "UDES",
    "version": "0.1",
    "depends": ["base", "stock", "stock_picking_batch", "udes_common"],
    "data": [
        "data/stock_data.xml",
        "data/warehouse.xml",
        "data/stock_config.xml",
        "data/locations.xml",
        "data/picking_types.xml",
        "data/routes.xml",
        "data/company.xml",
        "data/product_categories.xml",
        "views/product_views.xml",
        "views/stock_picking.xml",
        "views/stock_location_views.xml",
        "views/stock_template.xml",
        "views/stock_scrap_views.xml",
        "views/product_template.xml",
        "wizard/stock_backorder_confirmation_views.xml",
        "wizard/stock_immediate_transfer_views.xml",
    ],
}
